name: page_turn
description: Page Turn Widget | Add a page turn effect to widgets in your app.
version: 1.0.0
authors:
 - Flutter Community <community@flutter.zone>
 - Simon Lightfoot <simon@devangels.london>
 - Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/fluttercommunity/page_turn
maintainer: Rody Davis (@rodydavis)

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

